# Generated by Django 3.2.16 on 2026-01-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('year_max', models.DateField()),
                ('year_min', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'M'), ('D', 'Ж')], default='M', max_length=1)),
                ('birthday', models.DateField()),
                ('keys', models.CharField(blank=True, default='<django.db.models.fields.CharField><django.db.models.fields.CharField><django.db.models.fields.DateField>', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('type_run', models.CharField(choices=[('D', 'M'), ('N', 'Ж')], default='D', max_length=1)),
                ('data_run', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_place', models.IntegerField(max_length=4)),
                ('scores', models.IntegerField(max_length=4)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.season')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_place', models.IntegerField(max_length=4)),
                ('result_time', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.run')),
            ],
        ),
    ]
