# Generated by Django 3.2.16 on 2026-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_place',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores',
            name='result_place',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scores',
            name='scores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.IntegerField(),
        ),
    ]
