# Generated by Django 3.2.16 on 2026-01-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20260106_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='season',
            field=models.ForeignKey(default=1900, on_delete=django.db.models.deletion.PROTECT, to='person.season'),
        ),
        migrations.AddField(
            model_name='result',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.group'),
        ),
        migrations.AddField(
            model_name='run',
            name='season',
            field=models.ForeignKey(default=1900, on_delete=django.db.models.deletion.PROTECT, to='person.season'),
        ),
        migrations.AlterField(
            model_name='person',
            name='keys',
            field=models.CharField(blank=True, default='<django.db.models.fields.CharField><django.db.models.fields.CharField><django.db.models.fields.DateField>', max_length=64),
        ),
        migrations.AlterField(
            model_name='run',
            name='type_run',
            field=models.CharField(choices=[('D', 'День'), ('N', 'Ночь')], default='D', max_length=4),
        ),
        migrations.AlterField(
            model_name='scores',
            name='season',
            field=models.ForeignKey(default=1900, on_delete=django.db.models.deletion.PROTECT, to='person.season'),
        ),
    ]
