# Generated by Django 3.2.16 on 2026-01-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20260117_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.titlegroup'),
        ),
    ]
