# Generated by Django 3.2.16 on 2026-01-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_result_result_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='keys',
        ),
    ]
