# Generated by Django 3.2.16 on 2026-02-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_result_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('D', 'Ж')], default='M', max_length=1),
        ),
    ]
