# Generated by Django 3.2.16 on 2026-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_group_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
