# Generated by Django 3.2.16 on 2026-02-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_run_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='scores',
            field=models.FloatField(),
        ),
    ]
