# Generated by Django 3.2.16 on 2026-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_scores_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlegroup',
            name='title_eng',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
