# Generated by Django 3.2.16 on 2026-03-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_titlegroup_title_eng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlegroup',
            old_name='title_eng',
            new_name='name_file_html',
        ),
    ]
