# Generated by Django 3.2.16 on 2026-03-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_rename_title_eng_titlegroup_name_file_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'Группы участников'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'verbose_name': 'забег', 'verbose_name_plural': 'Забеги'},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name': 'очки', 'verbose_name_plural': 'Очки'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'сезон', 'verbose_name_plural': 'Сезоны'},
        ),
        migrations.AlterModelOptions(
            name='titlegroup',
            options={'verbose_name': 'заголовок', 'verbose_name_plural': 'Заголовки групп'},
        ),
        migrations.AlterField(
            model_name='group',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('D', 'Ж')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='group',
            name='season',
            field=models.ForeignKey(default=1900, on_delete=django.db.models.deletion.PROTECT, to='person.season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.titlegroup', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year_max',
            field=models.DateField(verbose_name='Год рождения до'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year_min',
            field=models.DateField(verbose_name='Год рождения от'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('D', 'Ж')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='result',
            name='distance',
            field=models.FloatField(verbose_name='Дистанция'),
        ),
        migrations.AlterField(
            model_name='result',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='result',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_place',
            field=models.IntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_time',
            field=models.IntegerField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='result',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.run', verbose_name='Забег'),
        ),
        migrations.AlterField(
            model_name='run',
            name='data_run',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='run',
            name='season',
            field=models.ForeignKey(default=1900, on_delete=django.db.models.deletion.PROTECT, to='person.season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='run',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='run',
            name='type_run',
            field=models.CharField(choices=[('D', 'День'), ('N', 'Ночь')], default='D', max_length=4, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='result_place',
            field=models.IntegerField(verbose_name='Занятое место'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='scores',
            field=models.FloatField(verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='season',
            field=models.ForeignKey(default=1900, on_delete=django.db.models.deletion.PROTECT, to='person.season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='titlegroup',
            name='name_file_html',
            field=models.CharField(max_length=20, verbose_name='Имя для файла html'),
        ),
        migrations.AlterField(
            model_name='titlegroup',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
