# Generated by Django 3.2.16 on 2026-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20260328_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='year_max',
            field=models.DateField(help_text='Старшая граница возраста (в 2025 г для групп 14-17 лет 2008)', verbose_name='Год рождения до'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year_min',
            field=models.DateField(help_text='Младшая граница возраста (в 2025 г для групп 14-17 лет 2011)', verbose_name='Год рождения от'),
        ),
        migrations.AlterField(
            model_name='titlegroup',
            name='name_file_html',
            field=models.CharField(help_text='Используется в /media/data_html; Имя должно быть латиницей без пробелов', max_length=20, verbose_name='Имя для файла html'),
        ),
    ]
